site_name: EGR 314 Ragul Raj's Data Sheet 
site_url: https://embedded-systems-design.github.io/EGR314DataSheetTemplate
repo_url: https://github.com/embedded-systems-design/EGR314DataSheetTemplate
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Requirements: 01-Requirements/Requirements.md
  - Block Diagram: 02-Block-Diagram/Block-Diagram.md
  - Major Components: 03-Component-Selection/Component-Selection.md
  - Microcontroller: 03-Component-Selection/Microcontroller.md
  - Power Budget: 03-Component-Selection/Power-Budget.md
  - BOM: 04-BOM/BOM.md
  - Schematic and PCB: 05-Schematic/schematic.md
  - Hardware V2.0: 06-Hardware-V2/Hardware-V2.md
  - API: 08-API/API.md
  - Resources: Resources/Resources.md
  - Reflection: 09-Reflection/Reflection.md
  - Appendix:
    - Overview: Appendix/index.md
    - Component Selection Process: Appendix/01-Componet-Selection/Component-Selection-Process.md
    - Microcontroller selection (ESP32): Appendix/02-Microcontroller-Selection/esp-32-table.md
    - Microcontroller selection (PIC): Appendix/02-Microcontroller-Selection/pic-table.md
    - Power Budget (appendix): Appendix/03-Power-Budget/Power-Budget.md
    - Example — basic markdown: Appendix/04-Examples-to-Remove/basic-markdown-examples.md
    - Example — charts: Appendix/04-Examples-to-Remove/charts.md
    - Example — another subfile: Appendix/04-Examples-to-Remove/another-subfile.md

theme:
  name: material
  custom_dir: custom_theme/
  palette:
    primary: blue
    accent: indigo
  font:
    text: Roboto
  logo: static/logo314.svg
  favicon: static/logo314.png

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow    
    - navigation.top
    - navigation.path
    - navigation.indexes
    - navigation.prune
    - content.action.edit
    - navigation.footer
#    - navigation.sections
#    - navigation.expand
#    - navigation.instant # doesn't work that well

markdown_extensions:
  - attr_list #add attributes using curly brackets to images, see https://squidfunk.github.io/mkdocs-material/reference/images/
  - md_in_html # see https://squidfunk.github.io/mkdocs-material/reference/images/
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tilde: {}
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

draft_docs: |
  **/*_unpublished.md
  **/*_draft.md
  **/*_draft**
  
plugins:
  - search
  - glightbox # allow resize images, see https://squidfunk.github.io/mkdocs-material/reference/images/

extra_css:
  - stylesheets/extra.css  

extra_javascript:
 - javascripts/mathjax.js
 - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    
not_in_nav: |
  static
  
copyright: "Copyright &copy; 2026 Ragul Raj RG"

extra:
  generator: false
  social:
    - icon: fontawesome/regular/file-code
      link: /2026_spring
      name: 2023 Site    
